# Netlify configuration file
[build]
  publish = "public"
  functions = "netlify/functions"



[dev]
  # serve local static files from public/
  publish = "public"
  functions = "netlify/functions"
  port = 8888
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
